- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  pacman:
    name: ["cmake", "pkg-config"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  pacman:
    name: ["unzip", "libtool", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  pacman:
    name: [ "compton", "curl", "htop", "lsof", "ccache", "dconf-editor", "pavucontrol", "moreutils" ]
  tags:
    - install
    - core

- name: Install Clang
  become: true
  pacman:
    name: ["clang"]
  tags:
    - install
    - neovim
    - core

