- name: Install ZSH
  become: yes
  ansible.builtin.package: 
    name:
      - "zsh"
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  become: yes
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks
